### ISSUE TITLE
android.renderscript.RSInvalidStateException: Calling RS with no Context active.

### ISSUE THREAD

**Issue by bjy520** [centerzx/ShapeBlurView#1]
android.renderscript.RSInvalidStateException: Calling RS with no Context active.
        at android.renderscript.RenderScript.validate(RenderScript.java:1249)
        at android.renderscript.Allocation.copyFrom(Allocation.java:996)
        at net.center.blurview.impl.AndroidStockBlurImpl.blur(AndroidStockBlurImpl.java:66)
        at net.center.blurview.ShapeBlurView.blur(ShapeBlurView.java:476)
        at net.center.blurview.ShapeBlurView$1.onPreDraw(ShapeBlurView.java:512)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3464)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9025)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
        at android.view.Choreographer.doCallbacks(Choreographer.java:946)
        at android.view.Choreographer.doFrame(Choreographer.java:875)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8292)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

在调用的时候出现了这个错误

**Comment by bjy520** [comment]
E/RenderScript: Failed to find hal setup entry points: undefined symbol: rsdHalAbort
2022-06-14 09:38:07.163 32237-32422 E/RenderScript: Failed to load runtime , loading default
2022-06-14 09:38:07.344 32237-32434 E/RenderScript: Failed to find hal setup entry points: undefined symbol: rsdHalAbort
2022-06-14 09:38:07.345 32237-32434 E/RenderScript: Failed to load runtime , loading default
2022-06-14 09:38:07.363 32237-32443 E/RenderScript: Failed to find hal setup entry points: undefined symbol: rsdHalAbort
2022-06-14 09:38:07.363 32237-32443 E/RenderScript: Failed to load runtime , loading default

**Comment by bjy520** [comment]
知道为啥了  用了glide 的BlurTransformation  这个   可能冲突了  关了就好了

**Comment by centerzx** [comment]
大佬厉害！google出了一个针对kotlin的图片加载库，coil，还是多不错的

> 知道为啥了 用了glide 的BlurTransformation 这个 可能冲突了 关了就好了
