### ISSUE TITLE
Calling RS with no Context active

### ISSUE THREAD

**Issue by devallever** [centerzx/ShapeBlurView#8]
android.renderscript.RSInvalidStateException: Calling RS with no Context active.
at android.renderscript.RenderScript.validate(RenderScript.java:1244)
at net.center.blurview.impl.AndroidStockBlurImpl.blur(AndroidStockBlurImpl.java:66)
at net.center.blurview.ShapeBlurView.blur(ShapeBlurView.java:477)
at net.center.blurview.ShapeBlurView$1.onPreDraw(ShapeBlurView.java:513)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)

**Comment by RoyZhang94** [comment]
> android.renderscript.RSInvalidStateException: Calling RS with no Context active. at android.renderscript.RenderScript.validate(RenderScript.java:1244) at net.center.blurview.impl.AndroidStockBlurImpl.blur(AndroidStockBlurImpl.java:66) at net.center.blurview.ShapeBlurView.blur(ShapeBlurView.java:477) at net.center.blurview.ShapeBlurView$1.onPreDraw(ShapeBlurView.java:513) at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)

解决了吗？我把 Glide 的 Blur 相关去掉也会出现，很奇怪
